# Generated by Django 5.0.4 on 2024-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_bot_tk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(editable=False, null=True, verbose_name='Ник TG')),
                ('query_txt', models.CharField(editable=False, verbose_name='Текст запроса')),
                ('result', models.BooleanField(editable=False, verbose_name='Результат поиска')),
            ],
            options={
                'verbose_name': 'Поиск ТК',
                'verbose_name_plural': 'Поиск ТК',
            },
        ),
    ]
