# Generated by Django 5.0.4 on 2024-05-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search_bot_tk',
            new_name='SearchBotTK',
        ),
    ]
