# Generated by Django 5.0.4 on 2024-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_rename_search_bot_tk_searchbottk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='searchbottk',
            options={'verbose_name': 'Поиск ТК', 'verbose_name_plural': 'Поисков ТК'},
        ),
    ]
