# Generated by Django 5.0.4 on 2024-07-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_supportbot_alter_searchbottk_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportBot',
        ),
    ]
