# Generated by Django 5.0.4 on 2024-07-02 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb1school', '0026_alter_leads_comment'),
        ('tg_bot', '0004_delete_supportbot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppBotTableRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000)])),
                ('first_menu', models.CharField(editable=False, verbose_name='Направление')),
                ('theme', models.CharField(editable=False, verbose_name='Тема обращения')),
                ('text_question', models.CharField(editable=False, verbose_name='Текст обращения')),
                ('work_eval', models.IntegerField(editable=False, verbose_name='Оценка ответа')),
                ('feedback', models.CharField(editable=False, verbose_name='Отзыв об ответе')),
                ('date_start', models.DateTimeField(editable=False, verbose_name='Дата обращения')),
                ('date_stop', models.DateTimeField(editable=False, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('INWORK', 'В работе'), ('WAITING', 'В ожидании'), ('COMPLET', 'Выполнен')], default='NEW', verbose_name='Статус')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nb1school.leads', verbose_name='Лид')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nb1school.learners', verbose_name='Ученик')),
                ('who_answered', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
            ],
            options={
                'verbose_name': 'Обращения в бот',
                'verbose_name_plural': 'Обращений в бот',
            },
        ),
    ]
