# Generated by Django 5.0.4 on 2024-07-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb1school', '0026_alter_leads_comment'),
        ('tg_bot', '0005_suppbottablerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nb1school.leads', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nb1school.learners', verbose_name='Ученик'),
        ),
    ]
