# Generated by Django 5.0.4 on 2024-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_alter_suppbottablerequests_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='date_stop',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Дата завершения'),
        ),
    ]
