# Generated by Django 5.0.4 on 2024-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_alter_suppbottablerequests_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
