# Generated by Django 5.0.4 on 2024-07-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_alter_suppbottablerequests_who_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='feedback',
            field=models.CharField(editable=False, null=True, verbose_name='Отзыв об ответе'),
        ),
    ]
