# Generated by Django 5.0.4 on 2024-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_alter_suppbottablerequests_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='status',
            field=models.CharField(choices=[('NEW', 'Открыт'), ('INWORK', 'В работе'), ('WAITING', 'В ожидании'), ('COMPLET', 'Выполнен')], default='NEW', verbose_name='Статус'),
        ),
    ]
