# Generated by Django 5.0.4 on 2024-07-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_alter_suppbottablerequests_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppbottablerequests',
            options={'verbose_name': 'Обращение в бот', 'verbose_name_plural': 'Обращения в бот'},
        ),
    ]
