# Generated by Django 5.0.4 on 2024-07-08 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0014_alter_suppbottablerequests_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(null=True, verbose_name='Имя Фамилия')),
                ('tg_username', models.CharField(editable=False, null=True, verbose_name='TG_Username')),
                ('tg_userid', models.IntegerField(editable=False, verbose_name='TG_UserID')),
                ('message', models.TextField(editable=False, verbose_name='Сообщение')),
                ('date_creat', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания отзыва')),
            ],
            options={
                'verbose_name': 'Отзывы/Предложения',
                'verbose_name_plural': 'Отзывов/Предложений',
            },
        ),
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='text_question',
            field=models.TextField(editable=False, verbose_name='Текст обращения'),
        ),
    ]
