# Generated by Django 5.0.4 on 2024-07-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0016_alter_feedback_options_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='from_who',
            field=models.CharField(choices=[('STAFF', 'Менеджер'), ('MENTOR', 'Наставник'), ('USER', 'Пользователь')], null=True, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='tg_bot.suppbottablerequests', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
