# Generated by Django 5.0.4 on 2024-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0017_chatmessages_edited_chatmessages_from_who_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='file',
            field=models.CharField(null=True, verbose_name='ID Файла'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='image',
            field=models.CharField(null=True, verbose_name='ID Фото'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='video',
            field=models.CharField(null=True, verbose_name='ID Видео'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='voice',
            field=models.CharField(null=True, verbose_name='ID Аудио'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
    ]
