# Generated by Django 5.0.4 on 2024-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0018_chatmessages_file_chatmessages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.CharField(null=True, verbose_name='ID Файла'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.CharField(null=True, verbose_name='ID Фото'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='video',
            field=models.CharField(null=True, verbose_name='ID Видео'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='voice',
            field=models.CharField(null=True, verbose_name='ID Аудио'),
        ),
    ]
