# Generated by Django 5.0.4 on 2024-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0020_chatmessages_caption_feedback_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(editable=False, null=True, verbose_name='Сообщение'),
        ),
    ]
