# Generated by Django 5.0.4 on 2024-07-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0021_alter_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tg_bot.feedback', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='tg_bot.suppbottablerequests', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправленно'),
        ),
    ]
