# Generated by Django 5.0.4 on 2024-07-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0022_chatmessages_feedback_alter_chatmessages_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='video',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='suppbottablerequests',
            name='text_question',
        ),
    ]
