# Generated by Django 5.0.4 on 2024-07-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0024_rename_feedback_chatmessages_feedbk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='from_who',
            field=models.CharField(choices=[('STAFF', 'Менеджер'), ('MENTOR', 'Наставник'), ('USER', 'Пользователь'), ('LEAD', 'Лид')], null=True, verbose_name='От кого'),
        ),
    ]
