# Generated by Django 5.0.4 on 2024-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0025_alter_chatmessages_from_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='feedbk',
        ),
        migrations.RemoveField(
            model_name='chatmessages',
            name='sbtr',
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='tg_userid',
            field=models.IntegerField(editable=False, null=True, verbose_name='TG_UserID'),
        ),
    ]
