# Generated by Django 5.0.4 on 2024-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0027_alter_chatmessages_from_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppbottablerequests',
            name='messages',
            field=models.ManyToManyField(to='tg_bot.chatmessages', verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='messages',
            field=models.ManyToManyField(to='tg_bot.chatmessages', verbose_name='Сообщения'),
        ),
    ]
