# Generated by Django 5.0.4 on 2024-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0030_alter_suppbottablerequests_who_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='tg_userid',
            field=models.BigIntegerField(editable=False, null=True, verbose_name='TG_UserID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tg_userid',
            field=models.BigIntegerField(editable=False, verbose_name='TG_UserID'),
        ),
    ]
