# Generated by Django 5.0.4 on 2024-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0031_alter_chatmessages_tg_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppbottablerequests',
            name='is_work',
            field=models.BooleanField(default=False, help_text='Находится в процессе диалога', verbose_name='В процессе'),
        ),
    ]
