# Generated by Django 5.0.4 on 2024-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0032_suppbottablerequests_is_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppbottablerequests',
            name='is_new_message',
            field=models.BooleanField(default=False, help_text='Новое сообщение от пользователя', verbose_name='Новое сообщение'),
        ),
        migrations.AlterField(
            model_name='suppbottablerequests',
            name='is_work',
            field=models.BooleanField(default=False, help_text='Ответственный находится в процессе диалога', verbose_name='В процессе'),
        ),
    ]
